version: '3'
services:
        client_web:
                container_name: client_web
                image: web
                build: ./web
                depends_on:
                        - server
        server:
                container_name: server
                image: server
                restart: always
                build: ./server
                ports:
                        - "8080:8080"
                links:
                        - mongo
        mongo:
                container_name: mongo
                image: mongo
                volumes:
                        - ./data:/data/db
                ports:
                        - "27017:27017"
