version: '3'
services:
        client_web:
                container_name: web
                build: ./web/
                ports:
                        - "8081:8081"
                depends_on:
                        - server
                        - mobile
        mobile_user:
                container_name: mobile
                build: ./mobile_user/
                depends_on:
                        - server
        server:
                container_name: server
                build: ./server/
                ports:
                        - "8080:8080"
        mongo:
                container_name: mongo
                image: mongo
